# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98c24b4b3644654e9ce9d6f4788ad2dac863b3ba43a6163d23ba0f829fe9615b1f2bf77cc8c48476ff9f0a0574183dd0a506230f56472eeb769f34a73f16c6a

test:
  secret_key_base: 53c1c98f29a5171645bce9b358551c75fcfa7cd15d14886e7e2830e2ff87106aa523331bdeb68a8fe4f7bcf4deeb17b30c5129c9aefa80aab8a3a40f03eb29bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
